"""add_response_text_to_ai_runs

Revision ID: f85a06401df1
Revises: 1bd079d55bf4
Create Date: 2026-09-21 18:39:49.718606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'f85a06401df1'
down_revision: Union[str, Sequence[str], None] = '1bd079d55bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_runs', sa.Column('response_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_runs', 'response_text')
    # ### end Alembic commands ###
